package refuel.oauth.exception

class AuthorizeChallengeException(msg: String, cause: Throwable = null) extends RuntimeException(msg, cause) {}
